import type { Job } from "@/types/Job";
import type { Specialist } from "@/types/Specialist";

export const jobs: Job[] = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Tashkent, Uzbekistan",
    type: "Full-time",
    salary: "$2,000 - $3,000 / month",
    description:
      "We are looking for a skilled Frontend Developer to join our team and help us build amazing user interfaces.",
    requirements: [
      "3+ years of experience with React",
      "Strong knowledge of JavaScript/TypeScript",
      "Experience with responsive design",
      "Understanding of CSS preprocessors",
    ],
    responsibilities: [
      "Develop new user-facing features",
      "Build reusable components and libraries",
      "Optimize applications for maximum speed and scalability",
      "Collaborate with backend developers and designers",
    ],
    postedDate: "2023-04-15",
    applicationDeadline: "2023-05-15",
    contactEmail: "careers@techcorp.com",
    logo: "/placeholder.svg?height=80&width=80",
    category: "Development",
    experience: "3+ years",
  },
  {
    id: "2",
    title: "UX/UI Designer",
    company: "DesignHub",
    location: "Remote",
    type: "Full-time",
    salary: "$1,800 - $2,500 / month",
    description:
      "Join our creative team to design beautiful and functional user experiences for our clients.",
    requirements: [
      "Portfolio demonstrating UX/UI skills",
      "Experience with Figma and Adobe Creative Suite",
      "Understanding of user-centered design principles",
      "Knowledge of frontend development is a plus",
    ],
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Collaborate with developers to implement designs",
      "Stay updated with latest design trends",
    ],
    postedDate: "2023-04-10",
    applicationDeadline: "2023-05-10",
    contactEmail: "jobs@designhub.com",
    logo: "/placeholder.svg?height=80&width=80",
    category: "Design",
    experience: "2+ years",
  },
  {
    id: "3",
    title: "Backend Developer",
    company: "ServerSolutions",
    location: "Samarkand, Uzbekistan",
    type: "Full-time",
    salary: "$2,200 - $3,200 / month",
    description:
      "We're seeking a talented Backend Developer to strengthen our engineering team.",
    requirements: [
      "Strong experience with Node.js and Express",
      "Knowledge of database systems (SQL and NoSQL)",
      "Understanding of RESTful APIs",
      "Experience with cloud services (AWS/Azure/GCP)",
    ],
    responsibilities: [
      "Design and implement backend services",
      "Optimize database queries and performance",
      "Ensure security of data and applications",
      "Collaborate with frontend developers",
    ],
    postedDate: "2023-04-05",
    applicationDeadline: "2023-05-05",
    contactEmail: "hr@serversolutions.com",
    logo: "/placeholder.svg?height=80&width=80",
    category: "Development",
    experience: "4+ years",
  },
  {
    id: "4",
    title: "Product Manager",
    company: "InnovateTech",
    location: "Tashkent, Uzbekistan",
    type: "Full-time",
    salary: "$2,500 - $3,500 / month",
    description:
      "Lead our product development process and help us create innovative solutions.",
    requirements: [
      "3+ years of product management experience",
      "Strong analytical and problem-solving skills",
      "Excellent communication abilities",
      "Technical background is a plus",
    ],
    responsibilities: [
      "Define product vision and strategy",
      "Gather and prioritize requirements",
      "Work closely with development and design teams",
      "Analyze market trends and competition",
    ],
    postedDate: "2023-04-01",
    applicationDeadline: "2023-05-01",
    contactEmail: "careers@innovatetech.com",
    logo: "/placeholder.svg?height=80&width=80",
    category: "Management",
    experience: "3+ years",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "CloudSystems",
    location: "Remote",
    type: "Contract",
    salary: "$25 - $35 / hour",
    description:
      "Help us build and maintain our cloud infrastructure and deployment pipelines.",
    requirements: [
      "Experience with AWS/Azure/GCP",
      "Knowledge of Docker and Kubernetes",
      "Familiarity with CI/CD tools",
      "Understanding of infrastructure as code",
    ],
    responsibilities: [
      "Set up and maintain cloud infrastructure",
      "Automate deployment processes",
      "Monitor system performance and security",
      "Troubleshoot and resolve infrastructure issues",
    ],
    postedDate: "2023-03-28",
    applicationDeadline: "2023-04-28",
    contactEmail: "jobs@cloudsystems.com",
    logo: "/placeholder.svg?height=80&width=80",
    category: "DevOps",
    experience: "2+ years",
  },
];

export const specialists: Specialist[] = [
  {
    id: "1",
    name: "Alisher Karimov",
    title: "Senior Frontend Developer",
    location: "Tashkent, Uzbekistan",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux"],
    experience: "5 years",
    education: [
      {
        degree: "Bachelor of Computer Science",
        institution: "Tashkent University of Information Technologies",
        year: "2018",
      },
    ],
    bio: "Passionate frontend developer with 5 years of experience building modern web applications. Specialized in React ecosystem and creating responsive, accessible user interfaces.",
    contactEmail: "alisher.karimov@example.com",
    phone: "+998 90 123 4567",
    avatar: "/placeholder.svg?height=200&width=200",
    portfolio: "https://alisherkarimov.dev",
    linkedin: "https://linkedin.com/in/alisherkarimov",
    github: "https://github.com/alisherkarimov",
    availability: "Available",
    hourlyRate: "$25 - $35",
  },
  {
    id: "2",
    name: "Dilnoza Rakhimova",
    title: "UX/UI Designer",
    location: "Remote",
    skills: ["Figma", "Adobe XD", "Sketch", "User Research", "Prototyping"],
    experience: "4 years",
    education: [
      {
        degree: "Bachelor of Design",
        institution: "National Institute of Fine Arts and Design",
        year: "2019",
      },
    ],
    bio: "Creative designer focused on creating intuitive and beautiful user experiences. I combine aesthetic sensibility with user-centered design principles to craft interfaces that users love.",
    contactEmail: "dilnoza.design@example.com",
    avatar: "/placeholder.svg?height=200&width=200",
    portfolio: "https://dilnozadesign.com",
    linkedin: "https://linkedin.com/in/dilnozadesign",
    availability: "Open to offers",
    hourlyRate: "$20 - $30",
  },
  {
    id: "3",
    name: "Rustam Khasanov",
    title: "Full Stack Developer",
    location: "Samarkand, Uzbekistan",
    skills: ["JavaScript", "Node.js", "React", "MongoDB", "Express", "AWS"],
    experience: "6 years",
    education: [
      {
        degree: "Master of Computer Engineering",
        institution: "Samarkand State University",
        year: "2017",
      },
    ],
    bio: "Full stack developer with expertise in both frontend and backend technologies. I enjoy building complete web applications from scratch and solving complex technical challenges.",
    contactEmail: "rustam.dev@example.com",
    phone: "+998 91 234 5678",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/rustamkhasanov",
    linkedin: "https://linkedin.com/in/rustamkhasanov",
    availability: "Open to offers",
    hourlyRate: "$30 - $40",
  },
  {
    id: "4",
    name: "Nodira Ismoilova",
    title: "Data Scientist",
    location: "Tashkent, Uzbekistan",
    skills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "Data Analysis",
      "SQL",
    ],
    experience: "3 years",
    education: [
      {
        degree: "Master of Data Science",
        institution: "Turin Polytechnic University in Tashkent",
        year: "2020",
      },
    ],
    bio: "Data scientist passionate about extracting insights from complex datasets. I specialize in building machine learning models and creating data visualizations that tell compelling stories.",
    contactEmail: "nodira.data@example.com",
    avatar: "/placeholder.svg?height=200&width=200",
    linkedin: "https://linkedin.com/in/nodiraismoilova",
    github: "https://github.com/nodiradata",
    availability: "Not available",
    hourlyRate: "$25 - $35",
  },
  {
    id: "5",
    name: "Timur Aliyev",
    title: "DevOps Engineer",
    location: "Remote",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform", "Linux"],
    experience: "4 years",
    education: [
      {
        degree: "Bachelor of Information Technology",
        institution: "Webster University in Tashkent",
        year: "2019",
      },
    ],
    bio: "DevOps engineer focused on automating infrastructure and streamlining deployment processes. I help teams deliver software faster and more reliably through modern DevOps practices.",
    contactEmail: "timur.devops@example.com",
    phone: "+998 93 345 6789",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/timuraliyev",
    linkedin: "https://linkedin.com/in/timuraliyev",
    availability: "Available",
    hourlyRate: "$30 - $40",
  },
];
